
[build-system]
requires = ["setuptools", "wheel"]

[project]
name = "ratfin"
version = "3.0.0"
description = "My awesome ratfin package."
authors = [
  { name = "Tinapat Limsila", email = "limsila.limsila@yahoo.com" },
]

[project.urls]
Source = "https://github.com/gametl/ratfin"